name: Actions

on:
  pull_request:
    paths:
      - .github/workflows/*

permissions:
  contents: read

jobs:
  action-lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: linkerd/dev/actions/setup-tools@v36
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - run: just-dev lint-actions
      - run: just-dev check-action-images
