name: Actions

on:
  pull_request:
    paths:
      - .github/workflows/*

permissions:
  contents: read

jobs:
  action-lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: linkerd/dev/actions/setup-tools@v36
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - run: just-dev lint-actions
      - run: just-dev check-action-images
