name: Release

on:
  pull_request:
    paths:
      - .github/workflows/release.yml
      - justfile
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: ghcr.io/linkerd/dev:v36-rust-musl
    steps:
      - id: meta
        shell: bash
        run: |
          set -eu
          shopt -s extglob
          ref="${{ github.ref }}"
          if [[ "$ref" == refs/tags/v+([0-9]).+([0-9]).+([0-9])?(-+([a-z0-9-])) ]]; then
            v=${ref##refs/tags/}
            echo version="$v" >> "$GITHUB_OUTPUT"
          else
            echo "Not a release version" >&2
          fi

      # XXX dev:v36-rust container doesn't include libjq
      - run: apt update && apt install -y --no-install-recommends jq

      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - run: just fetch

      - if: steps.meta.outputs.version
        run: |
          v=$(just crate-version)
          if [ "${v}" != '${{ steps.meta.outputs.version }}' ]; then
            echo "::error ::Crate version '${v}' does not match tag version '${{ steps.meta.outputs.version }}'"
            exit 1
          fi

      - run: echo PKG_DIR="$(mktemp -d "$RUNNER_TEMP/pkg.XXX")" >> "$GITHUB_ENV"
      - run: just profile=release target=x86_64-unknown-linux-musl package "$PKG_DIR"
      - run: just profile=release target=aarch64-unknown-linux-musl package "$PKG_DIR"
      - run: find "$PKG_DIR"/release -ls

      - if: steps.meta.outputs.version
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.meta.outputs.version }}
          files: ${{ env.PKG_DIR }}/release/*
          generate_release_notes: true

